### PR TITLE
Some updates to 0.2.x

### PR DESCRIPTION
**Pull request by SteinerOk**
- Update dependencies
- Add KotlinX Serialisation adapter
- Change orders of Coroutines adapters
- Added the posibility to send headers for socketIO
- Formating and typo fixes

### CODE REVIEW

**Comment by aaronweihe** [comment]
thanks for opening the pr. if you could break this down into multiple smaller PRs, I'd be happy to review!

**Comment by aaronweihe** [comment]
thanks for the PR. can you kindly split this into multiple PRs? e.g., a PR for kotlin update and a PR for moshi update etc

**Comment by SteinerOk** [comment]
@aaronweihe I think this PR is really too big. I can split deps updates to one PR, and features to others

**Comment by SecretsNetwork** [comment]
really need that kotlinx.serialization feature , when do you merge it?

**Comment by SteinerOk** [comment]
@SecretsNetwork This commit will not be merged, functions will be added separately, but first you need to update the libraries used, etc. I'm waiting for the review, etc.

**Comment by SecretsNetwork** [comment]
@SteinerOk i guess this project abandoned, how can install scarlet from your customized repo(SteinerOK/scarlet i mean) ?

**Pull request closed without merging**
